version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=localhost;Database=ECommerceDb;Username=postgres;Password=your_password
    depends_on:
      - postgres
    volumes:
      - './:/app'
    networks:
      - web
      - backend
    ports:
      - "8082:8082"

  postgres:
    image: postgres:15 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: ECommerceDb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
      - web
    ports:
      - '5432:5432'

  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8080:8080"
    networks:
     - web
     - backend

volumes:
  pgdata:


networks:
  web:
    external: true
  backend:
    driver: bridge